server:
  port: ${PORT:8080}
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/html,text/css,application/javascript,application/json
  servlet:
    context-path: /hotstock

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 5MB
  h2:
    console:
      enabled: true
  data:
    rest:
      basePath: /api
  datasource:
    url: jdbc:h2:~/.hotstock/database;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: hotstock
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    contexts: dev

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"

api:
  base-url: http://localhost:${server.port}${server.servlet.context-path}
  client-id: bc6edfe6-988c-490f-a70f-1e4dcf0d89a5
  client-secret: 68ad7524-56d2-48d4-bdc6-f1c1b11615a4

storage:
  location: .hotstock/storage
